parameters:
    csstoolkit.defaults:
        breakpoints:
            xs: 0
            sm: 576
            md: 768
            lg: 992
            xl: 1200
        colors:
            black: '#000000'
            white: '#ffffff'
        spacings:
            - 0
            - .25
            - .5
            - 1
            - 1.5
            - 3