services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]

    bohnmedia.css_toolkit_bundle.table:
        class: BohnMedia\CssToolkitBundle\Library\Table
        public: true
        arguments:
            - '%csstoolkit.defaults%'

    bohnmedia.css_toolkit_bundle.generator:
        class: BohnMedia\CssToolkitBundle\Library\Generator
        public: true
        arguments:
            - '%csstoolkit.defaults%'

    bohnmedia.css_toolkit_bundle.hooks:
        class: BohnMedia\CssToolkitBundle\Library\Hooks